# Generated by Django 3.2 on 2021-04-27 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0013_post_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node_block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_hash', models.CharField(blank=True, max_length=225)),
                ('nonce', models.CharField(blank=True, max_length=10, null=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver', models.CharField(blank=True, max_length=255, null=True)),
                ('cash', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.payment')),
            ],
        ),
    ]
