# Generated by Django 3.1.5 on 2021-03-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cash_received',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
