# Generated by Django 3.1.5 on 2021-03-24 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210313_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_hash', models.CharField(blank=True, max_length=225)),
                ('payment_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.payment')),
            ],
        ),
    ]
