# Generated by Django 3.1.5 on 2021-04-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210406_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='nonce',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
