# Generated by Django 3.1.5 on 2021-04-07 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_block_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
