# Generated by Django 3.1.5 on 2021-04-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_block_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='date_created',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
