# Generated by Django 3.1.7 on 2021-04-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210418_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sort_factor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
